### ISSUE TITLE
Final Capstone Kanban Board 👨‍💻 👨‍💻 👨‍💻 

### ISSUE THREAD

**Issue by tsheporamantso** [tsheporamantso/final-capstone-rails-api#5]
### Final Capstone Kanban Board 👨‍💻 👨‍💻 👨‍💻 
On this milestone 🗿 We have implemented the following :
- We are a team of 3 :
    - @evansnyamekye 
    - @George7h 
    - @tsheporamantso 
 
[Link](https://github.com/tsheporamantso/final-capstone-rails-api/projects?query=is%3Aopen) to our kanban board
[Link](https://github.com/tsheporamantso/final-capstone-react-front-end) to our front-end repo
[Link](https://github.com/tsheporamantso/final-capstone-rails-api) to our back-end repo

![image](https://github.com/tsheporamantso/final-capstone-rails-api/assets/110445380/8e6ef70c-39ec-46b7-8067-7f95d8f1fb7a)

![image](https://github.com/tsheporamantso/final-capstone-rails-api/assets/110445380/97760109-5bbc-4452-a48d-c3929e46427e)

**Comment by Meltrust** [comment]
Hi,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is not accesible:

![image](https://github.com/tsheporamantso/final-capstone-rails-api/assets/57421823/523e6ca9-053b-4c52-b9cc-84f98d941aa9)

Kindly, make it public and try again.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by tsheporamantso** [comment]
Hi Miguel

Please accept my most sincere apology, I've attached the correct link.

Thank you
Gladwin Ramantso.

________________________________

**Comment by Meltrust** [comment]
Hi,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!





![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

- [ ] According to the project requirements:

![image](https://github.com/tsheporamantso/final-capstone-rails-api/assets/57421823/d5b6825d-91a6-4b49-87c8-0ab0a8059e6a)

At the time of this review, these are the pointings:

- 32
- 22
- 25

Please notice that one member (tsheporamantso) has a lot more points than the other 2 members.

The general rule is that "No team member can have more than 5 points than any other member".

Kindly, tweak your pointings so we can meet this particular [requirement](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md). 👍 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Meltrust** [comment]
## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- Pointings are now equal✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
